defaults:
  keys: []
  starts_with: ["utm_"]

domains:
  airbnb.com:
    keys: ["unique_share_id"]

  facebook.com:
    keys: ["fbclid"]

  instagram.com:
    keys: ["igshid", "igsh"]

  linkedin.com:
    keys: ["rcm"]

  youtube.com:
  youtu.be:
    keys: ["si", "feature"]
    starts_with: ["utm_", "yt_"]  # overrides defaults with additional patterns

  default:
    keys: []