name: Deploy to VPS

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --package discord --bin boombot

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: boombot-binary
          path: target/release/boombot
          retention-days: 30

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: boombot-binary

      - name: Make binary executable
        run: chmod +x boombot

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Setup directories and environment
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
        run: |
          # First, ensure directories exist and have correct permissions
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.VPS_IP }} "
            sudo mkdir -p /home/ubuntu/boombot/{discord,data}
            sudo chown -R ubuntu:ubuntu /home/ubuntu/boombot
            sudo chmod -R 755 /home/ubuntu/boombot
          "

          # Then continue with environment setup
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.VPS_IP }} "
            # Create .env file
            cat > /home/ubuntu/boombot/discord/.env <<EOF
            DISCORD_TOKEN=${DISCORD_TOKEN}
            DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
            DATABASE_PATH=/home/ubuntu/boombot/data/rules.db
            EOF
            chmod 600 /home/ubuntu/boombot/discord/.env
          "

      - name: Deploy binary to VPS
        run: |
          # Copy the binary to the server
          scp -o StrictHostKeyChecking=no boombot ubuntu@${{ secrets.VPS_IP }}:/home/ubuntu/boombot/discord/
          
          # Update service configuration and restart
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.VPS_IP }} "
            # Update systemd service configuration
            sudo tee /etc/systemd/system/boombot.service <<EOF
            [Unit]
            Description=Boombot Discord Service
            After=network.target

            [Service]
            Type=simple
            User=ubuntu
            WorkingDirectory=/home/ubuntu/boombot/discord
            EnvironmentFile=/home/ubuntu/boombot/discord/.env
            ExecStart=/home/ubuntu/boombot/discord/boombot
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOF

            # Make binary executable and restart service
            chmod +x /home/ubuntu/boombot/discord/boombot
            sudo systemctl daemon-reload
            sudo systemctl restart boombot
          "