[package]
name = "cleaner"
version = "0.1.0"
edition = "2024"

[dependencies]
url = "2.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rusqlite = { version = "0.36.0", features = ["bundled"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
bcrypt = "0.17.0"